### Test simulate sale for a device
POST http://localhost:8080/server/v1/simulation/device/183b1ae3-08d4-45e2-a7b1-be3410898943/sale
Content-Type: application/json

{
  "items_sold": 5
}

### Response should be:
# HTTP/1.1 200 OK
# {
#   "status": "success",
#   "data": {
#     // message data
#   }
# }